<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Templatedesign
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top'); ?>
<?php if ($_menu): ?>
    <div class="container visible-xs">
        <nav class="navbar navbar-default navbar-main" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <span class="sr-only"><?php echo $this->__('Toggle Navigation') ?></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <?php echo $_menu ?>
                </ul>
            </div>
        </nav>
    </div>
<?php endif ?>
<?php $_menuDesktop = $this->getHtmlDesktop('nav-menu-item'); ?>
<?php if ($_menuDesktop): ?>
    <div class="container hidden-xs">
        <nav class="nav-menu">
            <ul>
                <?php if ($department = Mage::getStoreConfig('templatedesign/navigation/department')): ?>
                    <li class="nav-menu-item all-department">
                        <a class="nav-menu-item-link">
                            <i class="fa fa-chevron-circle-down">
                            </i><?php echo $this->__('Veja todo shopping') ?></a>
                        <div class="nav-submenu">
                            <div class="nav-submenu-border col-md-12">

                                <?php $_menuAllDesktop = $this->getHtmlAllDesktop('nav-menu-item'); ?>
                                <?php if ($_menuAllDesktop): ?>
                                    <?php echo $_menuAllDesktop ?>
                                <?php endif ?>
                                <div class="footer clearfix">
                                    <ul>
                                        <li class="bottom-item">
                                            <a href="#">Lista de casamento</a>
                                        </li>
                                        <li class="bottom-item spacing">
                                            <a href="#" class="allShoppingSignUp">Cadastre-se</a>
                                        </li>
                                        <li class="bottom-item">
                                            <a href="#">Garantia estendida</a>
                                        </li>
                                        <li class="bottom-item last">
                                            <a href="#">Vale presente</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endif; ?>
                <?php echo $_menuDesktop ?>
            </ul>
        </nav>
    </div>
<?php endif ?>