<?php
/**
 * @var $this		Mage_Catalog_Block_Product_View_Media
 * @var $product	Mage_Catalog_Model_Product
 */
?>
<?php
$product = $this->getProduct();
$helper = $this->helper('catalog/output');

// Get the base image path
$baseImageFile = ($product->getImage() != 'no_selection' and $product->getImage()) ? $product->getImage() : false;

$galleryImages = array();

// Process the gallery images
foreach ($this->getGalleryImages() as $image) {
    if ($baseImageFile and $image->getFile() === $baseImageFile) {
        continue;
    }

    $galleryImages[] = $image;
}

$index = 0;
$config = Mage::getStoreConfig('templatedesign');

//cloud Zoom config
$config['cloudzoom']['position'] = empty($config['cloudzoom']['position']) ? 'right' : $config['cloudzoom']['position'];
$config['cloudzoom']['lens_opacity'] = intval($config['cloudzoom']['lens_opacity']) / 100;
$config['cloudzoom']['tint_opacity'] = intval($config['cloudzoom']['tint_opacity']) / 100;
$config['cloudzoom']['zoom_width'] = empty($config['cloudzoom']['zoom_width']) ? '736' : $config['cloudzoom']['zoom_width'];
$config['cloudzoom']['zoom_height'] = empty($config['cloudzoom']['zoom_height']) ? '460' : $config['cloudzoom']['zoom_height'];
$config['cloudzoom']['big_image_width'] = empty($config['cloudzoom']['big_image_width']) ? '736' : $config['cloudzoom']['big_image_width'];
$config['cloudzoom']['big_image_height'] = empty($config['cloudzoom']['big_image_height']) ? '587' : $config['cloudzoom']['big_image_height'];
?>

<?php if ($config['cloudzoom']['position'] == 'inside') : ?>
    <style>
        .cloud-zoom-big { margin:0; -moz-box-shadow:none; -webkit-box-shadow:none; box-shadow:none; }
    </style>
    <?php
endif;

$cloudZoom = array(
    "position:'" . $config['cloudzoom']['position'] . "'",
    "showTitle:false",
    "lensOpacity:" . $config['cloudzoom']['lens_opacity']
);
if ($config['cloudzoom']['zoom_width'] > 0) {
    $cloudZoom[] = "zoomWidth:" . $config['cloudzoom']['zoom_width'];
}
if ($config['cloudzoom']['zoom_height'] > 0) {
    $cloudZoom[] = "zoomHeight:" . $config['cloudzoom']['zoom_height'];
}

if ($config['cloudzoom']['tint_color']) {
    $cloudZoom[] = "tint:'" . $config['cloudzoom']['tint_color'] . "',tintOpacity:" . $config['cloudzoom']['tint_opacity'];
}
if ($config['cloudzoom']['soft_focus'] > 0) {
    $cloudZoom[] = "softFocus:" . $config['cloudzoom']['soft_focus'];
}

if (empty($config['cloudzoom']['big_image_width']) || empty($config['cloudzoom']['big_image_height'])) {
    if (empty($config['cloudzoom']['big_image_width']) || $config['cloudzoom']['big_image_width'] > 1200) {
        $config['cloudzoom']['big_image_width'] = 1200;
    }
    if (empty($config['cloudzoom']['big_image_height'])) {
        $config['cloudzoom']['big_image_height'] = $this->helper('templatedesign/image')->calculateHeight($config['cloudzoom']['big_image_width']);
    }
}

$baseImageSize = array('x' => $config['cloudzoom']['width'], 'y' => $config['cloudzoom']['height'],);
$galleryImageSize = array('x' => 95, 'y' => 60,);
$zoomSize = array('x' => $config['cloudzoom']['big_image_width'], 'y' => $config['cloudzoom']['big_image_height'],);
?>
<?php if ($baseImageFile): ?>
    <div class="product-image product-image-zoom">
        <a href="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($zoomSize['x'], $zoomSize['y']) ?>" class="cloud-zoom" id="cloud_zoom" data-rel="<?php echo implode($cloudZoom, ','); ?>" data-index="<?php echo $index++ ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($baseImageSize['x'], $baseImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>">
        </a>
    </div>
<?php endif ?>

<?php if ($galleryImages): ?>
    <div class="more-views">
        <ul>
            <?php if ($baseImageFile): ?>
            <li>
                <a href="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($zoomSize['x'], $zoomSize['y']) ?>" class='cloud-zoom-gallery' data-index="<?php echo $index++ ?>" data-rel="useZoom: 'cloud_zoom', smallImage: '<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($baseImageSize['x'], $baseImageSize['y']); ?>' ">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($image->getLabel()) ?>">
                </a>
            </li>
            <?php endif ?>
            <?php foreach ($galleryImages as $image): ?>
                <li>
                    <a href="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($zoomSize['x'], $zoomSize['y']) ?>" class='cloud-zoom-gallery' data-index="<?php echo $index++ ?>" data-rel="useZoom: 'cloud_zoom', smallImage: '<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($baseImageSize['x'], $baseImageSize['y']); ?>' ">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($image->getLabel()) ?>">
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php

 endif ?>
