<?php
/**
 * @var $this		Mage_Catalog_Block_Product_View_Media
 * @var $product	Mage_Catalog_Model_Product
 */
?>
<?php
$product = $this->getProduct();
$helper = $this->helper('catalog/output');

// Get the base image path
$baseImageFile = ($product->getImage() != 'no_selection' and $product->getImage()) ? $product->getImage() : false;

$galleryImages = array();

// Process the gallery images
foreach ($this->getGalleryImages() as $image) {
    if ($baseImageFile and $image->getFile() === $baseImageFile) {
        continue;
    }

    $galleryImages[] = $image;
}

$index = 0;
$config = Mage::getStoreConfig('templatedesign');

//cloud Zoom config
$config['cloudzoom']['position'] = empty($config['cloudzoom']['position']) ? 'right' : $config['cloudzoom']['position'];
$config['cloudzoom']['lens_opacity'] = empty($config['cloudzoom']['lens_opacity']) ? '0.4' : $config['cloudzoom']['lens_opacity'];
$config['cloudzoom']['tint_opacity'] = empty($config['cloudzoom']['tint_opacity']) ? '0.4' : $config['cloudzoom']['tint_opacity'];
$config['cloudzoom']['zoom_width'] = empty($config['cloudzoom']['zoom_width']) ? '736' : $config['cloudzoom']['zoom_width'];
$config['cloudzoom']['zoom_height'] = empty($config['cloudzoom']['zoom_height']) ? '460' : $config['cloudzoom']['zoom_height'];
$config['cloudzoom']['big_image_width'] = empty($config['cloudzoom']['big_image_width']) ? '736' : $config['cloudzoom']['big_image_width'];
$config['cloudzoom']['big_image_height'] = empty($config['cloudzoom']['big_image_height']) ? '587' : $config['cloudzoom']['big_image_height'];
if (empty($config['cloudzoom']['big_image_width']) || empty($config['cloudzoom']['big_image_height'])) {
    if (empty($config['cloudzoom']['big_image_width']) || $config['cloudzoom']['big_image_width'] > 1200) {
        $config['cloudzoom']['big_image_width'] = 1200;
    }
    if (empty($config['cloudzoom']['big_image_height'])) {
        $config['cloudzoom']['big_image_height'] = $this->helper('templatedesign/image')->calculateHeight($config['cloudzoom']['big_image_width']);
    }
}

switch ($config['cloudzoom']['position']) {
    case "top":
        $zoomWindowPosition = "14";
        $zoomType = "window";
        break;
    case "right":
        $zoomWindowPosition = "2";
        $zoomType = "window";
        break;
    case "bottom":
        $zoomWindowPosition = "6";
        $zoomType = "window";
        break;
    case "left":
        $zoomWindowPosition = "10";
        $zoomType = "window";
        break;
    case "lens":
        $zoomWindowPosition = "1";
        $zoomType = "lens";
        break;
    default:
        $zoomWindowPosition = "1";
        $zoomType = "window";
}
$baseImageSize = array('x' => $config['cloudzoom']['width'], 'y' => $config['cloudzoom']['height'],);
$galleryImageSize = array('x' => 95, 'y' => 60,);
$zoomSize = array('x' => $config['cloudzoom']['big_image_width'], 'y' => $config['cloudzoom']['big_image_height'],);
?>
<?php if ($baseImageFile): ?>
    <div class="product-image product-image-zoom">
        <?php echo $this->helper('templatedesign')->getLabel($product); ?>
        <img data-zoom-image="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($zoomSize['x'], $zoomSize['y']) ?>"   src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($baseImageSize['x'], $baseImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>" class='elevatezoom'>
    </div>
<?php endif ?>

<?php if ($galleryImages): ?>
    <div class="more-views" id="gallery_01f">
        <ul>
            <?php if ($baseImageFile): ?>
                <li>
                    <a data-zoom-image="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($zoomSize['x'], $zoomSize['y']) ?>" class='elevatezoom-gallery' data-index="<?php echo $index++ ?>" data-image="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($baseImageSize['x'], $baseImageSize['y']); ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($image->getLabel()) ?>">
                    </a>
                </li>
            <?php endif ?>
            <?php foreach ($galleryImages as $image): ?>
                <li>
                    <a data-zoom-image="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($zoomSize['x'], $zoomSize['y']) ?>" class='elevatezoom-gallery' data-index="<?php echo $index++ ?>" data-image="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($baseImageSize['x'], $baseImageSize['y']); ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $this->htmlEscape($image->getLabel()) ?>">
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <script>
        jQuery(document).ready(function () {
            jQuery('.elevatezoom').elevateZoom({
                //zoomActivation: 'hover', // Can also be click (PLACEHOLDER FOR NEXT VERSION)
                zoomWindowWidth: <?php echo $config['cloudzoom']['zoom_width'] ?>,
                zoomWindowHeight: <?php echo $config['cloudzoom']['zoom_height'] ?>,
                //zoomWindowPosition: <?php echo $zoomWindowPosition ?>,
                //zoomWindowBgColour: '#fff',
                borderSize: 2,
                showLens: true,
                borderColour: '#f0f0f0',
                lensBorderSize: 1,
                lensBorderColour: '#000',
                zoomType: '<?php echo $zoomType ?>', //window is default,  also "lens" available -
                lensOpacity: <?php echo $config['cloudzoom']['lens_opacity'] ?>, //opacity of the lens
                tintColour: '<?php echo $config['cloudzoom']['tint_color'] ?>', //default tint color, can be anything, red, #ccc, rgb(0,0,0)
                tintOpacity: <?php echo $config['cloudzoom']['tint_opacity'] ?>, //opacity of the tint
                gallery:'gallery_01f',
                galleryActiveClass: 'active',
                cursor:'pointer', // user should set to what they want the cursor as, if they have set a click function
                responsive:true,
                containLensZoom: true
            });
        });
    </script>
    <?php
 endif ?>
